version: "3.4"
services:
  frontend:
    build: .
    entrypoint: ["./run.sh"]
    environment:
      VITE_PORT: 8080
      VITE_API_HOST:
      VITE_API_PORT:
    ports:
      - "8080:8080"
    networks:
      - 03--user-management

networks:
  03--user-management:
    external: true
