/* tslint:disable */
/* eslint-disable */
/**
 * User Management API
 * API docs
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserDto
     */
    birthdate?: string;
}

/**
 * Check if a given object implements the UpdateUserDto interface.
 */
export function instanceOfUpdateUserDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserDtoFromJSON(json: any): UpdateUserDto {
    return UpdateUserDtoFromJSONTyped(json, false);
}

export function UpdateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'birthdate': !exists(json, 'birthdate') ? undefined : json['birthdate'],
    };
}

export function UpdateUserDtoToJSON(value?: UpdateUserDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'address': value.address,
        'email': value.email,
        'birthdate': value.birthdate,
    };
}

