name: pull request
on:
  pull_request


jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: 'v18.14.1'
          cache: 'yarn'
      - run: yarn
      - run: yarn lint
      - run: yarn test:ts
      - run: yarn test:cov

  docker:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:$(git rev-parse --short=10 HEAD) .
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:$(git rev-parse --short=10 HEAD)
